### ISSUE TITLE
Unexpected error: no supported device was found

### ISSUE THREAD

**Issue by vinn-chege** [Soul-Remix/NetWarden#1]
Getting the error as shown in the screenshot. Any workaround for this.. tried on both wi-fi and ethernet devices. Npcap is installed as well.. i am behind an openwrt router

![Screenshot 2024-03-29 124314](https://github.com/Soul-Remix/NetWarden/assets/121945862/f7432b9e-d714-4d3c-83d3-1b70648ea1a2)

**Comment by Soul-Remix** [comment]
Thank you for bringing this to my attention. I'll begin investigating it further. I'll keep you updated on any progress.

**Comment by Soul-Remix** [comment]
@vinn-chege I've introduced a new release that allow users to manually select their preferred device. Now, you can easily switch devices either through the intuitive interface (TUI) or via the command line using: './netwarden set-device <device name>'. 
In case the system fails to detect a compatible device automatically, the select device screen will prompt automatically. Your feedback on this release would be greatly appreciated after giving it a test run.

**Comment by vinn-chege** [comment]
@Soul-Remix thank you for the update. I've tried the new update and I'm happy to report that it works fine and I'm able to select networking devices both on the tui and cli. it has also eliminated the delay that was there as the program tried to scan for devices on the network.
