### ISSUE TITLE
High CPU usage on Linux.

### ISSUE THREAD

**Issue by vinn-chege** [Soul-Remix/NetWarden#3]
The Linux version of the program is quite CPU intensive. I've tried running on different distros and seem to be getting the same results. The Windows version however seems to run well with minimal resource use.
![Screenshot_20240404_103247-1](https://github.com/Soul-Remix/NetWarden/assets/121945862/a43b475b-0946-4c0b-87b6-22ef52136480)
![Screenshot_20240404_103452](https://github.com/Soul-Remix/NetWarden/assets/121945862/9b03fa2f-7f48-43dc-9de4-079e23611989)

**Comment by Soul-Remix** [comment]
I spotted this issue and dug deeper—it seems tied to this Terminal.Gui issue: https://github.com/gui-cs/Terminal.Gui/issues/3018

I'm gonna give Terminal.Gui v2 a shot and cross my fingers it sorts things out.

**Comment by Soul-Remix** [comment]
@vinn-chege I Updated the Terminal.Gui version and i noticed a significant decrease in cpu usage on linux, Please feel free to test the new release.

I'm also expecting new bugs to popup after this migration to v2, so please don't hesitate to open a new issue if you face any problems.

**Comment by vinn-chege** [comment]
thanks for the update... I've tested on Linux and can confirm that CPU usage seems stable and no longer revving up my fans:)... I'll keep testing to see if I find any other issues within the program.

**Comment by Mersid** [comment]
Heya! Just ran into this problem when deploying a program to Linux. Just to confirm, is this fixed in v2? What's the experience like on that version?
